<?php
if (!get_option('vv_sitemap_installed')) {
$sections = [
  ['name' => 'Core Pages & Services', 'links' => [
    ['https://vardhinivastu.in/about/', 'About'],
    ['https://vardhinivastu.in/banaswadi/', 'Banaswadi'],
    ['https://vardhinivastu.in/bannerghatta-road/', 'Bannerghatta Road'],
    ['https://vardhinivastu.in/basavanagudi/', 'Basavanagudi'],
    ['https://vardhinivastu.in/benefits-of-vastu-shastra/', 'Benefits Of Vastu Shastra'],
    ['https://vardhinivastu.in/brahmasthan-vastu/', 'Brahmasthan Vastu'],
    ['https://vardhinivastu.in/btm-layout/', 'Btm Layout'],
    ['https://vardhinivastu.in/case-studies/', 'Case Studies'],
    ['https://vardhinivastu.in/contact/', 'Contact'],
    ['https://vardhinivastu.in/credentials/', 'Credentials'],
    ['https://vardhinivastu.in/disclaimer/', 'Disclaimer'],
    ['https://vardhinivastu.in/east-facing-house-vastu/', 'East Facing House Vastu'],
    ['https://vardhinivastu.in/five-elements-of-vastu-shastra/', 'Five Elements Of Vastu Shastra'],
    ['https://vardhinivastu.in/frequency-based-spatial-remedies/', 'Frequency Based Spatial Remedies'],
    ['https://vardhinivastu.in/hebbal/', 'Hebbal'],
    ['https://vardhinivastu.in/', 'Home'],
    ['https://vardhinivastu.in/indiranagar/', 'Indiranagar'],
    ['https://vardhinivastu.in/kr-puram/', 'Kr Puram'],
    ['https://vardhinivastu.in/lecher-antenna-geopathic-stress/', 'Lecher Antenna Geopathic Stress'],
    ['https://vardhinivastu.in/malleswaram/', 'Malleswaram'],
    ['https://vardhinivastu.in/marathahalli/', 'Marathahalli'],
    ['https://vardhinivastu.in/media/', 'Media'],
    ['https://vardhinivastu.in/nagarbhavi/', 'Nagarbhavi'],
    ['https://vardhinivastu.in/north-east-facing-house-vastu-complete-guide/', 'North East Facing House Vastu Complete Guide'],
    ['https://vardhinivastu.in/north-facing-house-vastu/', 'North Facing House Vastu'],
    ['https://vardhinivastu.in/north-west-facing-house-vastu/', 'North West Facing House Vastu'],
    ['https://vardhinivastu.in/online-vastu-consultation/', 'Online Vastu Consultation'],
    ['https://vardhinivastu.in/origin-of-vastu-shastra/', 'Origin Of Vastu Shastra'],
    ['https://vardhinivastu.in/our-methodology/', 'Our Methodology'],
    ['https://vardhinivastu.in/privacy-policy/', 'Privacy Policy'],
    ['https://vardhinivastu.in/rajajinagar/', 'Rajajinagar'],
    ['https://vardhinivastu.in/refund-policy/', 'Refund Policy'],
    ['https://vardhinivastu.in/sarjapur-road/', 'Sarjapur Road'],
    ['https://vardhinivastu.in/services/', 'Services'],
    ['https://vardhinivastu.in/soma-vastu/', 'Soma Vastu'],
    ['https://vardhinivastu.in/south-east-facing-house-vastu/', 'South East Facing House Vastu'],
    ['https://vardhinivastu.in/south-facing-house-vastu/', 'South Facing House Vastu'],
    ['https://vardhinivastu.in/south-west-facing-house-vastu-complete-guide/', 'South West Facing House Vastu Complete Guide'],
    ['https://vardhinivastu.in/terms-and-conditions/', 'Terms And Conditions'],
    ['https://vardhinivastu.in/vardhini-vastu/', 'Vardhini Vastu'],
    ['https://vardhinivastu.in/vardhini-vastu-reviews/', 'Vardhini Vastu Reviews'],
    ['https://vardhinivastu.in/vastu-2bhk-flat-bangalore/', 'Vastu 2Bhk Flat Bangalore'],
    ['https://vardhinivastu.in/vastu-as-a-science/', 'Vastu As A Science'],
    ['https://vardhinivastu.in/vastu-assets-apartments/', 'Vastu Assets Apartments'],
    ['https://vardhinivastu.in/vastu-assets-lifestyle/', 'Vastu Assets Lifestyle'],
    ['https://vardhinivastu.in/vastu-assets-west-bangalore/', 'Vastu Assets West Bangalore'],
    ['https://vardhinivastu.in/vastu-avani-allure/', 'Vastu Avani Allure'],
    ['https://vardhinivastu.in/vastu-avani-group-apartments/', 'Vastu Avani Group Apartments'],
    ['https://vardhinivastu.in/vastu-avani-north-bangalore/', 'Vastu Avani North Bangalore'],
    ['https://vardhinivastu.in/vastu-brigade-apartments/', 'Vastu Brigade Apartments'],
    ['https://vardhinivastu.in/vastu-brigade-north-bangalore/', 'Vastu Brigade North Bangalore'],
    ['https://vardhinivastu.in/vastu-brigade-south-bangalore/', 'Vastu Brigade South Bangalore'],
    ['https://vardhinivastu.in/vastu-compass-directions/', 'Vastu Compass Directions'],
    ['https://vardhinivastu.in/vastu-consultation-fees/', 'Vastu Consultation Fees'],
    ['https://vardhinivastu.in/vastu-crystals/', 'Vastu Crystals'],
    ['https://vardhinivastu.in/vastu-extended-corner/', 'Vastu Extended Corner'],
    ['https://vardhinivastu.in/vastu-faq/', 'Vastu Faq'],
    ['https://vardhinivastu.in/vastu-fish-tank/', 'Vastu Fish Tank'],
    ['https://vardhinivastu.in/vastu-gated-community-apartments/', 'Vastu Gated Community Apartments'],
    ['https://vardhinivastu.in/vastu-geopathic-stress-5-essential-remedies-for-earth-energy-defects/', 'Vastu Geopathic Stress 5 Essential Remedies For Earth Energy Defects'],
    ['https://vardhinivastu.in/vastu-godrej-apartments/', 'Vastu Godrej Apartments'],
    ['https://vardhinivastu.in/vastu-godrej-north-bangalore/', 'Vastu Godrej North Bangalore'],
    ['https://vardhinivastu.in/vastu-godrej-whitefield/', 'Vastu Godrej Whitefield'],
    ['https://vardhinivastu.in/vastu-hiranandani-apartments/', 'Vastu Hiranandani Apartments'],
    ['https://vardhinivastu.in/vastu-hiranandani-parks/', 'Vastu Hiranandani Parks'],
    ['https://vardhinivastu.in/vastu-irregular-plot/', 'Vastu Irregular Plot'],
    ['https://vardhinivastu.in/vastu-l-shaped-plot/', 'Vastu L Shaped Plot'],
    ['https://vardhinivastu.in/vastu-laughing-buddha/', 'Vastu Laughing Buddha'],
    ['https://vardhinivastu.in/vastu-luxury-apartments-bangalore/', 'Vastu Luxury Apartments Bangalore'],
    ['https://vardhinivastu.in/vastu-missing-corner/', 'Vastu Missing Corner'],
    ['https://vardhinivastu.in/vastu-north-east-cut/', 'Vastu North East Cut'],
    ['https://vardhinivastu.in/vastu-plants/', 'Vastu Plants'],
    ['https://vardhinivastu.in/vastu-prestige-apartments/', 'Vastu Prestige Apartments'],
    ['https://vardhinivastu.in/vastu-prestige-north-bangalore/', 'Vastu Prestige North Bangalore'],
    ['https://vardhinivastu.in/vastu-prestige-south-bangalore/', 'Vastu Prestige South Bangalore'],
    ['https://vardhinivastu.in/vastu-prestige-whitefield/', 'Vastu Prestige Whitefield'],
    ['https://vardhinivastu.in/vastu-purusha-mandala/', 'Vastu Purusha Mandala'],
    ['https://vardhinivastu.in/vastu-pyramid/', 'Vastu Pyramid'],
    ['https://vardhinivastu.in/vastu-remedies/', 'Vastu Remedies'],
    ['https://vardhinivastu.in/vastu-shastra-directions/', 'Vastu Shastra Directions'],
    ['https://vardhinivastu.in/vastu-shastra-history/', 'Vastu Shastra History'],
    ['https://vardhinivastu.in/vastu-shastra-house-plan/', 'Vastu Shastra House Plan'],
    ['https://vardhinivastu.in/vastu-shastra-the-complete-guide/', 'Vastu Shastra The Complete Guide'],
    ['https://vardhinivastu.in/vastu-sobha-apartments/', 'Vastu Sobha Apartments'],
    ['https://vardhinivastu.in/vastu-sobha-city-apartments/', 'Vastu Sobha City Apartments'],
    ['https://vardhinivastu.in/vastu-sobha-east-bangalore/', 'Vastu Sobha East Bangalore'],
    ['https://vardhinivastu.in/vastu-south-west-cut/', 'Vastu South West Cut'],
    ['https://vardhinivastu.in/vastu-t-junction/', 'Vastu T Junction'],
    ['https://vardhinivastu.in/vastu-to-prevent-accidents/', 'Vastu To Prevent Accidents'],
    ['https://vardhinivastu.in/vastu-tortoise/', 'Vastu Tortoise'],
    ['https://vardhinivastu.in/vastu-unlocked/', 'Vastu Unlocked'],
    ['https://vardhinivastu.in/vastu-vidya-the-complete-knowledge-system-of-vastu-shastra/', 'Vastu Vidya The Complete Knowledge System Of Vastu Shastra'],
    ['https://vardhinivastu.in/vastu-vs-feng-shui/', 'Vastu Vs Feng Shui'],
    ['https://vardhinivastu.in/vastu-wind-chime/', 'Vastu Wind Chime'],
    ['https://vardhinivastu.in/vastu-yantras/', 'Vastu Yantras'],
    ['https://vardhinivastu.in/what-is-vastu-shastra/', 'What Is Vastu Shastra'],
    ['https://vardhinivastu.in/why-vardhini-vastu/', 'Why Vardhini Vastu'],
    ['https://vardhinivastu.in/why-vastu-shastra/', 'Why Vastu Shastra'],
    ['https://vardhinivastu.in/yelahanka/', 'Yelahanka'],
  ]],
  ['name' => 'Vastu & Space Correction Guides', 'links' => [
    ['https://vardhinivastu.in/vastu-for-accounts-department/', 'Accounts Department'],
    ['https://vardhinivastu.in/vastu-for-aquarium/', 'Aquarium'],
    ['https://vardhinivastu.in/vastu-for-balcony/', 'Balcony'],
    ['https://vardhinivastu.in/vastu-for-bar-area/', 'Bar Area'],
    ['https://vardhinivastu.in/vastu-for-basement/', 'Basement'],
    ['https://vardhinivastu.in/vastu-for-bathroom/', 'Bathroom'],
    ['https://vardhinivastu.in/vastu-for-bedroom/', 'Bedroom'],
    ['https://vardhinivastu.in/vastu-for-boiler-furnace/', 'Boiler Furnace'],
    ['https://vardhinivastu.in/vastu-for-car-parking/', 'Car Parking'],
    ['https://vardhinivastu.in/vastu-for-career/', 'Career'],
    ['https://vardhinivastu.in/vastu-for-children/', 'Children'],
    ['https://vardhinivastu.in/vastu-for-childrens-room/', 'Childrens Room'],
    ['https://vardhinivastu.in/vastu-for-clinic/', 'Clinic'],
    ['https://vardhinivastu.in/vastu-for-colors/', 'Colors'],
    ['https://vardhinivastu.in/vastu-for-conference-room/', 'Conference Room'],
    ['https://vardhinivastu.in/vastu-for-curtains/', 'Curtains'],
    ['https://vardhinivastu.in/vastu-for-dining-room/', 'Dining Room'],
    ['https://vardhinivastu.in/vastu-for-dressing-room/', 'Dressing Room'],
    ['https://vardhinivastu.in/vastu-for-dustbin/', 'Dustbin'],
    ['https://vardhinivastu.in/vastu-for-architects/', 'Vastu for Architects'],
    ['https://vardhinivastu.in/industrial-vastu-bangalore/', 'Factory'],
    ['https://vardhinivastu.in/vastu-for-file-room/', 'File Room'],
    ['https://vardhinivastu.in/vastu-for-flat-and-apartment-complete-guide/', 'Flat And Apartment Complete Guide'],
    ['https://vardhinivastu.in/vastu-for-furniture-layout/', 'Furniture Layout'],
    ['https://vardhinivastu.in/vastu-for-game-room/', 'Game Room'],
    ['https://vardhinivastu.in/vastu-for-garage/', 'Garage'],
    ['https://vardhinivastu.in/vastu-for-garden/', 'Garden'],
    ['https://vardhinivastu.in/vastu-for-guest-room/', 'Guest Room'],
    ['https://vardhinivastu.in/vastu-for-health/', 'Health'],
    ['https://vardhinivastu.in/vastu-for-home-gym/', 'Home Gym'],
    ['https://vardhinivastu.in/vastu-for-home-office/', 'Home Office'],
    ['https://vardhinivastu.in/vastu-for-home-theater/', 'Home Theater'],
    ['https://vardhinivastu.in/vastu-for-hotel/', 'Hotel'],
    ['https://vardhinivastu.in/house-number-numerology/', 'House Number Numerology'],
    ['https://vardhinivastu.in/vastu-for-kitchen/', 'Kitchen'],
    ['https://vardhinivastu.in/vastu-for-living-room/', 'Living Room'],
    ['https://vardhinivastu.in/vastu-for-main-entrance/', 'Main Entrance'],
    ['https://vardhinivastu.in/vastu-for-mandir-at-home/', 'Mandir At Home'],
    ['https://vardhinivastu.in/vastu-for-marriage/', 'Marriage'],
    ['https://vardhinivastu.in/vastu-for-master-bedroom/', 'Master Bedroom'],
    ['https://vardhinivastu.in/vastu-for-mirrors/', 'Mirrors'],
    ['https://vardhinivastu.in/vastu-for-new-home/', 'New Home'],
    ['https://vardhinivastu.in/vastu-for-northeast-toilet/', 'Northeast Toilet'],
    ['https://vardhinivastu.in/vastu-for-office/', 'Office'],
    ['https://vardhinivastu.in/vastu-for-office-pantry-kitchen/', 'Office Pantry Kitchen'],
    ['https://vardhinivastu.in/vastu-for-office-washroom/', 'Office Washroom'],
    ['https://vardhinivastu.in/vastu-for-owners-cabin/', 'Owners Cabin'],
    ['https://vardhinivastu.in/vastu-for-pets-corner/', 'Pets Corner'],
    ['https://vardhinivastu.in/vastu-for-plot-selection/', 'Plot Selection'],
    ['https://vardhinivastu.in/vastu-for-pooja-room/', 'Pooja Room'],
    ['https://vardhinivastu.in/vastu-for-pregnancy/', 'Pregnancy'],
    ['https://vardhinivastu.in/vastu-for-production-area/', 'Production Area'],
    ['https://vardhinivastu.in/vastu-for-reception-desk/', 'Reception Desk'],
    ['https://vardhinivastu.in/vastu-for-relationship/', 'Relationship'],
    ['https://vardhinivastu.in/vastu-for-restaurant/', 'Restaurant'],
    ['https://vardhinivastu.in/vastu-for-safe-and-locker/', 'Safe And Locker'],
    ['https://vardhinivastu.in/vastu-for-septic-tank/', 'Septic Tank'],
    ['https://vardhinivastu.in/vastu-for-server-room/', 'Server Room'],
    ['https://vardhinivastu.in/vastu-for-shoe-rack/', 'Shoe Rack'],
    ['https://vardhinivastu.in/vastu-for-shop/', 'Shop'],
    ['https://vardhinivastu.in/vastu-for-showroom/', 'Showroom'],
    ['https://vardhinivastu.in/vastu-for-sleep/', 'Sleep'],
    ['https://vardhinivastu.in/vastu-for-staircase/', 'Staircase'],
    ['https://vardhinivastu.in/vastu-for-students/', 'Students'],
    ['https://vardhinivastu.in/vastu-for-study-room/', 'Study Room'],
    ['https://vardhinivastu.in/vastu-for-sustainable-homes/', 'Sustainable Homes'],
    ['https://vardhinivastu.in/vastu-for-swimming-pool/', 'Swimming Pool'],
    ['https://vardhinivastu.in/vastu-for-temple/', 'Temple'],
    ['https://vardhinivastu.in/vastu-for-toilet/', 'Toilet'],
    ['https://vardhinivastu.in/vastu-for-tv-electronic-items/', 'Tv Electronic Items'],
    ['https://vardhinivastu.in/vastu-for-utility-room/', 'Utility Room'],
    ['https://vardhinivastu.in/vastu-for-wall-art-paintings/', 'Wall Art Paintings'],
    ['https://vardhinivastu.in/vastu-for-wall-clock/', 'Wall Clock'],
    ['https://vardhinivastu.in/vastu-for-warehouse/', 'Warehouse'],
    ['https://vardhinivastu.in/vastu-for-water-tank/', 'Water Tank'],
    ['https://vardhinivastu.in/vastu-for-wealth/', 'Wealth'],
    ['https://vardhinivastu.in/vastu-for-windows/', 'Windows'],
  ]],
  ['name' => 'Bangalore Service Locations', 'links' => [
    ['https://vardhinivastu.in/vastu-consultant-akshayanagar/', 'Akshayanagar'],
    ['https://vardhinivastu.in/vastu-consultant-anekal-industrial-area/', 'Anekal Industrial Area'],
    ['https://vardhinivastu.in/vastu-consultant-attibele/', 'Attibele'],
    ['https://vardhinivastu.in/vastu-consultant-bagalur/', 'Bagalur'],
    ['https://vardhinivastu.in/vastu-consultant-banashankari/', 'Banashankari'],
    ['https://vardhinivastu.in/vastu-consultant-bannerghatta/', 'Bannerghatta'],
    ['https://vardhinivastu.in/vastu-consultant-bellandur/', 'Bellandur'],
    ['https://vardhinivastu.in/best-vastu-consultant-bangalore/', 'Best Bangalore'],
    ['https://vardhinivastu.in/vastu-consultant-bidadi-industrial-area/', 'Bidadi Industrial Area'],
    ['https://vardhinivastu.in/vastu-consultant-bommanahalli/', 'Bommanahalli'],
    ['https://vardhinivastu.in/vastu-consultant-bommasandra-industrial/', 'Bommasandra Industrial'],
    ['https://vardhinivastu.in/vastu-consultant-bommasandra-jigani-link-road/', 'Bommasandra Jigani Link Road'],
    ['https://vardhinivastu.in/vastu-consultant-bommasandra-phase-2-3/', 'Bommasandra Phase 2 3'],
    ['https://vardhinivastu.in/vastu-consultant-brookefield/', 'Brookefield'],
    ['https://vardhinivastu.in/vastu-consultant-dasarahalli/', 'Dasarahalli'],
    ['https://vardhinivastu.in/vastu-consultant-devanahalli/', 'Devanahalli'],
    ['https://vardhinivastu.in/vastu-consultant-dobbaspet-industrial/', 'Dobbaspet Industrial'],
    ['https://vardhinivastu.in/vastu-consultant-domlur/', 'Domlur'],
    ['https://vardhinivastu.in/vastu-consultant-electronic-city/', 'Electronic City'],
    ['https://vardhinivastu.in/vastu-consultant-hal/', 'Hal'],
    ['https://vardhinivastu.in/vastu-consultant-harohalli-industrial/', 'Harohalli Industrial'],
    ['https://vardhinivastu.in/vastu-consultant-hennur/', 'Hennur'],
    ['https://vardhinivastu.in/vastu-consultant-hsr-layout/', 'Hsr Layout'],
    ['https://vardhinivastu.in/vastu-consultant-jakkur/', 'Jakkur'],
    ['https://vardhinivastu.in/vastu-consultant-jayanagar/', 'Jayanagar'],
    ['https://vardhinivastu.in/vastu-consultant-jigani-1st-phase/', 'Jigani 1St Phase'],
    ['https://vardhinivastu.in/vastu-consultant-jigani-2nd-phase/', 'Jigani 2Nd Phase'],
    ['https://vardhinivastu.in/vastu-consultant-jigani-anekal-corridor/', 'Jigani Anekal Corridor'],
    ['https://vardhinivastu.in/vastu-consultant-jigani-industrial/', 'Jigani Industrial'],
    ['https://vardhinivastu.in/vastu-consultant-jp-nagar/', 'Jp Nagar'],
    ['https://vardhinivastu.in/vastu-consultant-kadugodi/', 'Kadugodi'],
    ['https://vardhinivastu.in/vastu-consultant-kalyan-nagar/', 'Kalyan Nagar'],
    ['https://vardhinivastu.in/vastu-consultant-kengeri/', 'Kengeri'],
    ['https://vardhinivastu.in/vastu-consultant-kiadb-devanahalli-aerospace/', 'Kiadb Devanahalli Aerospace'],
    ['https://vardhinivastu.in/vastu-consultant-kiadb-doddaballapura/', 'Kiadb Doddaballapura'],
    ['https://vardhinivastu.in/vastu-consultant-kiadb-hoskote/', 'Kiadb Hoskote'],
    ['https://vardhinivastu.in/vastu-consultant-kiadb-narsapura/', 'Kiadb Narsapura'],
    ['https://vardhinivastu.in/vastu-consultant-kiadb-nelamangala/', 'Kiadb Nelamangala'],
    ['https://vardhinivastu.in/vastu-consultant-kiadb-tumkur-road/', 'Kiadb Tumkur Road'],
    ['https://vardhinivastu.in/vastu-consultant-kiadb-whitefield/', 'Kiadb Whitefield'],
    ['https://vardhinivastu.in/vastu-consultant-kogilu/', 'Kogilu'],
    ['https://vardhinivastu.in/vastu-consultant-konanakunte/', 'Konanakunte'],
    ['https://vardhinivastu.in/vastu-consultant-koramangala/', 'Koramangala'],
    ['https://vardhinivastu.in/vastu-consultant-kumaraswamy-layout/', 'Kumaraswamy Layout'],
    ['https://vardhinivastu.in/vastu-consultant-mahadevapura/', 'Mahadevapura'],
    ['https://vardhinivastu.in/vastu-consultant-mathikere/', 'Mathikere'],
    ['https://vardhinivastu.in/vastu-consultant-nagasandra-industrial/', 'Nagasandra Industrial'],
    ['https://vardhinivastu.in/vastu-consultant-padmanabhanagar/', 'Padmanabhanagar'],
    ['https://vardhinivastu.in/vastu-consultant-peenya/', 'Peenya'],
    ['https://vardhinivastu.in/vastu-consultant-peenya-1st-stage/', 'Peenya 1St Stage'],
    ['https://vardhinivastu.in/vastu-consultant-peenya-2nd-stage/', 'Peenya 2Nd Stage'],
    ['https://vardhinivastu.in/vastu-consultant-peenya-industrial-area/', 'Peenya Industrial Area'],
    ['https://vardhinivastu.in/vastu-consultant-rajajinagar-industrial/', 'Rajajinagar Industrial'],
    ['https://vardhinivastu.in/vastu-consultant-rr-nagar/', 'Rr Nagar'],
    ['https://vardhinivastu.in/vastu-consultant-rt-nagar/', 'Rt Nagar'],
    ['https://vardhinivastu.in/vastu-consultant-sanjay-nagar/', 'Sanjay Nagar'],
    ['https://vardhinivastu.in/vastu-consultant-seegehalli/', 'Seegehalli'],
    ['https://vardhinivastu.in/vastu-consultant-thanisandra/', 'Thanisandra'],
    ['https://vardhinivastu.in/vastu-consultant-uttarahalli/', 'Uttarahalli'],
    ['https://vardhinivastu.in/vastu-consultant-varthur/', 'Varthur'],
    ['https://vardhinivastu.in/vastu-consultant-vijayanagar/', 'Vijayanagar'],
    ['https://vardhinivastu.in/what-does-a-vastu-consultant-do/', 'What Does A Do'],
    ['https://vardhinivastu.in/vastu-consultant-whitefield/', 'Whitefield'],
    ['https://vardhinivastu.in/vastu-consultant-yeshwanthpur/', 'Yeshwanthpur'],
  ]],
  ['name' => 'National & International Hubs', 'links' => [
    ['https://vardhinivastu.in/vastu-consultant-abu-dhabi/', 'Abu Dhabi'],
    ['https://vardhinivastu.in/vastu-consultant-ahmedabad/', 'Ahmedabad'],
    ['https://vardhinivastu.in/vastu-consultant-australia/', 'Australia'],
    ['https://vardhinivastu.in/best-vastu-consultant-india/', 'Best India'],
    ['https://vardhinivastu.in/vastu-consultant-canada/', 'Canada'],
    ['https://vardhinivastu.in/vastu-consultant-chandigarh/', 'Chandigarh'],
    ['https://vardhinivastu.in/vastu-consultant-chennai/', 'Chennai'],
    ['https://vardhinivastu.in/vastu-consultant-coimbatore/', 'Coimbatore'],
    ['https://vardhinivastu.in/vastu-consultant-delhi/', 'Delhi'],
    ['https://vardhinivastu.in/vastu-consultant-dubai/', 'Dubai'],
    ['https://vardhinivastu.in/vastu-consultant-gurugram/', 'Gurugram'],
    ['https://vardhinivastu.in/vastu-consultant-hyderabad/', 'Hyderabad'],
    ['https://vardhinivastu.in/vastu-consultant-jaipur/', 'Jaipur'],
    ['https://vardhinivastu.in/vastu-consultant-kochi/', 'Kochi'],
    ['https://vardhinivastu.in/vastu-consultant-kolkata/', 'Kolkata'],
    ['https://vardhinivastu.in/vastu-consultant-mangaluru/', 'Mangaluru'],
    ['https://vardhinivastu.in/vastu-consultant-mumbai/', 'Mumbai'],
    ['https://vardhinivastu.in/vastu-consultant-mysuru/', 'Mysuru'],
    ['https://vardhinivastu.in/vastu-consultant-noida/', 'Noida'],
    ['https://vardhinivastu.in/vastu-consultant-pune/', 'Pune'],
    ['https://vardhinivastu.in/vastu-consultant-qatar/', 'Qatar'],
    ['https://vardhinivastu.in/vastu-consultant-singapore/', 'Singapore'],
    ['https://vardhinivastu.in/vastu-consultant-uk/', 'Uk'],
    ['https://vardhinivastu.in/vastu-consultant-usa/', 'Usa'],
  ]],
  ['name' => 'Vastu Insights & Articles', 'links' => [
    ['https://vardhinivastu.in/vastu-insights/', 'Vastu Insights'],
    ['https://vardhinivastu.in/vastu-for-apartments-bangalore/', 'Vastu For Apartments Bangalore'],
    ['https://vardhinivastu.in/vastu-mistakes-new-home-construction/', 'Vastu Mistakes New Home Construction'],
  ]],
];

// Build HTML
$a = '<a href="%s" style="color:#374151;text-decoration:none;font-size:.95rem;padding:10px 14px;background:#f9fafb;border:1px solid #e5e7eb;border-radius:6px;display:block;transition:all .2s" onmouseover="this.style.background=\'#fff7ed\';this.style.borderColor=\'#fdba74\';this.style.color=\'#ea580c\'" onmouseout="this.style.background=\'#f9fafb\';this.style.borderColor=\'#e5e7eb\';this.style.color=\'#374151\'">%s</a>';
$html = '<div class="site-directory-container" style="max-width:1200px;margin:40px auto;padding:20px;font-family:Inter,sans-serif">';
$html .= '<h1 style="font-size:2.25rem;font-weight:800;color:#1f2937;margin-bottom:12px;text-align:center">Website Sitemap &amp; Directory</h1>';
$html .= '<p style="color:#6b7280;font-size:1.05rem;text-align:center;margin-bottom:40px;max-width:600px;margin-left:auto;margin-right:auto">Access all residential, commercial, and industrial Vastu consulting services, guides, and neighbourhood locations served by Vardhini Vastu.</p>';
foreach ($sections as $sec) {
    $html .= '<div style="margin-bottom:40px">';
    $html .= '<h2 style="font-size:1.4rem;font-weight:700;color:#ea580c;border-bottom:2px solid #ffedd5;padding-bottom:8px;margin-bottom:16px">' . esc_html($sec['name']) . '</h2>';
    $html .= '<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:12px">';
    foreach ($sec['links'] as $lnk) {
        $html .= sprintf($a, esc_url($lnk[0]), esc_html($lnk[1]));
    }
    $html .= '</div></div>';
}
$html .= '</div>';

// Create or update page
$existing = get_page_by_path('sitemap');
if ($existing) {
    $id = wp_update_post(['ID' => $existing->ID, 'post_content' => $html, 'post_status' => 'publish']);
    echo 'Updated ID: ' . $id;
} else {
    $id = wp_insert_post(['post_title' => 'Sitemap', 'post_content' => $html, 'post_status' => 'publish', 'post_type' => 'page', 'post_name' => 'sitemap']);
    echo 'Created ID: ' . $id;
}
update_post_meta($id, 'rank_math_title', 'Sitemap');
update_post_meta($id, 'rank_math_description', 'Complete sitemap and directory of all Vardhini Vastu pages - services, guides, Bangalore locations, and articles.');
update_post_meta($id, 'rank_math_robots', ['noindex']);
do_action('litespeed_purge_all');
  update_option('vv_sitemap_installed', true);
}
